import json
C = []
def c(id, script, inp="", opts=(), files=None, **kw):
    d = {"id": id, "opts": list(opts), "script": script, "input": inp}
    if files is not None: d["files"] = files
    d.update(kw); C.append(d)
c("F5", "s/a**/X/", "aaa\n")
c("F6", "s/a/\\x4/", "a\n"); c("F6b", "s/a/\\o7/", "a\n"); c("F6c", "s/a/\\d9/", "a\n"); c("F6d", "s/a/\\x4b/", "a\n")
c("F7", "l 2", "\t\n", ["-n"]); c("F7b", "l 3", "a\tb\n", ["-n"]); c("F7c", "l 4", "\\\\\\\n", ["-n"])
c("F8", "/[\\/]/p", "\\\n/\n", ["-n"]); c("F8b", "s/[\\/]/X/g", "a\\b/c\n")
c("F10", "N", "a\n"); c("F10b", "N", "a\n", ["-n"]); c("F10c", "$!N;N", "a\nb\n")
c("F11", "s\\a\\b\\p", "a\n", ["-n"]); c("F11b", "y\\a\\b\\", "a\n")
c("F12", "2,9c X", "1\n2\n3\n")
c("F13", "2s/x/y/; //p", "x\nz\n", ["-n"]); c("F13b", "//p", "x\n", ["-n"])
c("F14", "/a^b/p", "a^b\n", ["-E", "-n"]); c("F14b", "/(^a)/p", "a\n", ["-E", "-n"])
c("F15", "/[a\\-c]/p", "-\n", ["-n"]); c("F15b", "s/[a\\-c]/X/g", "a-b\\c\n")
c("V1", "a \\t", "x\n"); c("V1i", "i \\t", "x\n"); c("V1c", "c \\t", "x\n"); c("V1b", "a\\\nA\\tB", "x\n")
c("V2", "y/\\x61/Z/", "a\n"); c("V2b", "y/\\o142\\d099/YZ/", "abc\n")
c("V3", "s/[[:xdigit:]]/X/", "f\n")
c("V4", "\tp", "x\n")
c("V17", "s/[[:lower:]]/X/gp", "Ab\n", ["-n"])
c("V19", "i X;d", "a\n"); c("V19c", "c X;d", "a\n")
c("V20", "s#x#\\##", "x\n")
c("V21", "y,ab,x\\,,", "ab\n"); c("V21b", "y/ab/\\\\\\//", "ab\n")
c("V22a", "a\tX", "x\n"); c("V22i", "i\tX", "x\n"); c("V22c", "c\tX", "x\n")
c("V23", "c\\\n\\\\", "x\n")
c("V24a", "a\\\nA\\\nB\ns/x/y/", "x\n"); c("V24c", "1c\\\nA\\\nB\n2s/y/z/", "x\ny\n")
c("V25", "i hello;d", "a\n"); c("V25c", "c hello;p", "a\n")
c("V26", "b x;: x ;s/a/C/", "a\n")
c("V27", "\;a\;b;p", "a;b\n", ["-n"])
c("V28", "s/a\\?b/X/", "a?b\n", ["-E"])
c("V29", "/(a$)/p", "a\n", ["-E", "-n"]); c("V29b", "/\\(a$\\)/p", "a\n", ["-n"])
c("V30", "s/[[:lower:]]/X/gp", "Ab\n", ["-n"])
c("V31", "l 12", "\\" * 7 + "\n", ["-n"])
c("V32", "s/\\(b\\?\\)-/\\l\\1X/g", "a--b-\n")
c("V33", "N;/a.b/Mp", "a\nb\n", ["-n"]); c("V34", "N;/a$/Mp", "a\nb\n", ["-n"])
json.dump(C, open("probe.json", "w"), indent=0)
