#!/usr/bin/env python3
"""Refresh the searchable, per-task gallery snapshot from the live portal backend."""

from __future__ import annotations

import datetime
import importlib.util
import json
import pathlib
import re
import urllib.parse


HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[2]
OUT = ROOT / "mined-candidates" / "gallery_tasks_snapshot.md"


def load_portal_helpers():
    path = HERE / "refresh_gallery_taxonomy.py"
    spec = importlib.util.spec_from_file_location("gallery_taxonomy_refresh", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def fetch_all(helper, backend: str, key: str, view: str, select: str):
    headers = {"apikey": key, "Authorization": f"Bearer {key}"}
    rows = []
    offset = 0
    while True:
        query = urllib.parse.urlencode(
            {"select": select, "order": "id", "offset": offset, "limit": 1000}
        )
        page = json.loads(helper.get(f"{backend}/rest/v1/{view}?{query}", headers))
        if isinstance(page, dict):
            raise RuntimeError(f"{view} query failed: {page}")
        rows.extend(page)
        if len(page) < 1000:
            return rows
        offset += 1000


def clean(value) -> str:
    if value is None:
        return ""
    if isinstance(value, (list, dict)):
        value = json.dumps(value, ensure_ascii=False, sort_keys=True)
    return re.sub(r"\s+", " ", str(value)).strip().replace("|", "\\|")


def render(curated, inspiration) -> str:
    today = datetime.date.today().isoformat()
    lines = [
        "# Live Terminus gallery task snapshot",
        "",
        "> AUTO-GENERATED by `.agent/skills/task-miner/refresh_gallery_snapshot.py`; do not hand-edit.",
        f"> Snapshot date: {today}. Curated rows: {len(curated)}. Inspiration rows: {len(inspiration)}.",
        "> Source: the same public Supabase views used by the Terminus portal. Public credentials are not stored here.",
        "",
        "Use this file for semantic novelty searches. A title match is not conclusive: compare the description,",
        "behavioral contract, work surface, interaction, input surface, oracle, verifier, and failure mode.",
        "",
        "## Curated gallery (`v_tasks_with_priorities`)",
        "",
    ]
    for row in curated:
        taxonomy = " / ".join(
            filter(None, (clean(row.get("category")), clean(row.get("subcategory")), clean(row.get("subsubcategory"))))
        )
        lines.append(
            f"- **{clean(row.get('title')) or '(untitled)'}** "
            f"[id={clean(row.get('id'))}; taxonomy={taxonomy or '-'}] — "
            f"{clean(row.get('description')) or '(no description)'}"
        )

    lines.extend(["", "## Inspiration pool (`task_inspiration_v2`)", ""])
    for row in inspiration:
        meta = "; ".join(
            part
            for part in (
                f"id={clean(row.get('id'))}",
                f"type={clean(row.get('type')) or '-'}",
                f"subtypes={clean(row.get('subtypes')) or '[]'}",
                f"languages={clean(row.get('languages')) or '[]'}",
                f"repo={clean(row.get('repo')) or '-'}",
                f"source={clean(row.get('source_url')) or '-'}",
            )
            if part
        )
        lines.append(
            f"- **{clean(row.get('title')) or '(untitled)'}** [{meta}] — "
            f"{clean(row.get('description')) or '(no description)'}"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    helper = load_portal_helpers()
    backend, key = helper.discover()
    curated = fetch_all(
        helper,
        backend,
        key,
        "v_tasks_with_priorities",
        "id,title,description,category,subcategory,subsubcategory,created_at",
    )
    inspiration = fetch_all(
        helper,
        backend,
        key,
        "task_inspiration_v2",
        "id,title,description,type,subtypes,languages,repo,source_url,created_at,is_milestone",
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(curated, inspiration), encoding="utf-8")
    print(f"wrote {OUT}: curated={len(curated)} inspiration={len(inspiration)}")


if __name__ == "__main__":
    main()
