#!/usr/bin/env python3
"""Refresh mined-candidates/gallery_taxonomy.md from the LIVE portal gallery.

The Terminus task gallery (/portal/tasks) renders data from the portal's Supabase
backend. This script re-discovers the backend each run so it survives portal
redeploys (the JS bundle hash and even the anon key can rotate):

  1. GET index.html  -> find the current /assets/index-*.js bundle path
  2. GET that bundle -> extract the Supabase URL + public anon JWT (role=anon)
  3. Paginate v_tasks_with_priorities (3-level taxonomy) and task_inspiration_v2
     (type / subtypes / languages) via PostgREST
  4. Regenerate mined-candidates/gallery_taxonomy.md, stamped with today's date

No third-party deps (urllib only). Run from anywhere:
    python3 skills/task-miner/refresh_gallery_taxonomy.py
"""
import json, re, sys, os, collections, datetime, urllib.request

SITE = "https://snorkel-ai.github.io/Terminus-EC-Training-stateful"
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(REPO, "mined-candidates", "gallery_taxonomy.md")
UA = {"User-Agent": "task-miner-taxonomy-refresh"}

KEBAB = {
    "Build & Dependency Management": "build-and-dependency-management",
    "Data Processing & Scripting": "data-processing",
    "Debugging & Troubleshooting": "debugging",
    "Interactive Challenges & Games": "games",
    "Machine Learning & AI": "machine-learning",
    "Scientific Computing & Analysis": "scientific-computing",
    "Security & Cryptography": "security",
    "Software Engineering & Development": "software-engineering",
    "System Setup & Configuration": "system-administration",
    "Large Codebase Tasks": "(milestone / large-codebase lane — no kebab in current skill)",
}
FIVE = ["Long Context", "Tool Specific", "API Integration", "DB Interaction", "UI Building"]


def get(url, headers=None, timeout=60):
    req = urllib.request.Request(url, headers={**UA, **(headers or {})})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.read().decode("utf-8", "replace")


def discover():
    """Return (supabase_url, anon_key) by parsing the live bundle."""
    idx = get(f"{SITE}/index.html")
    m = re.search(r'src="(/Terminus-EC-Training-stateful/assets/index-[^"]+\.js)"', idx)
    if not m:
        sys.exit("FATAL: could not find the JS bundle path in index.html (portal layout changed)")
    bundle = get("https://snorkel-ai.github.io" + m.group(1))
    su = re.search(r"https://[a-z0-9]+\.supabase\.co", bundle)
    key = re.search(r"eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+", bundle)
    if not su or not key:
        sys.exit("FATAL: could not extract Supabase url/anon key from bundle (changed backend?)")
    return su.group(0), key.group(0)


def fetch_all(sb, key, view, select):
    headers = {"apikey": key, "Authorization": f"Bearer {key}"}
    rows, off = [], 0
    while True:
        url = f"{sb}/rest/v1/{view}?select={select}&order=id&offset={off}&limit=1000"
        page = json.loads(get(url, headers))
        if isinstance(page, dict):  # PostgREST error object
            sys.exit(f"FATAL: {view} query error: {page}")
        rows.extend(page)
        if len(page) < 1000:
            return rows
        off += 1000


def build_markdown(V, I, today):
    vcat = collections.Counter(r.get("category") for r in V)
    itype = collections.Counter(r.get("type") for r in I)
    tree = collections.defaultdict(lambda: collections.defaultdict(collections.Counter))
    for r in V:
        tree[r.get("category")][r.get("subcategory")][r.get("subsubcategory")] += 1
    langs = collections.Counter()
    for r in I:
        for x in (r.get("languages") or []):
            langs[x] += 1
    sub5 = collections.Counter()
    for r in I:
        for s in (r.get("subtypes") or []):
            sub5[s] += 1
    mile = collections.Counter(r.get("is_milestone") for r in I)

    o = []
    a = o.append
    a("# Task Gallery Taxonomy (authoritative category/subtype reference for task-miner)\n")
    a("The Terminus task gallery (`/portal/tasks`) is the live benchmark corpus. This file")
    a("is the **authoritative taxonomy menu** the miner aligns candidates to. Pair it with")
    a("`gallery_tasks_snapshot.md` (the per-task novelty/dedupe list).\n")
    a("> AUTO-GENERATED by `skills/task-miner/refresh_gallery_taxonomy.py`. Do not hand-edit;")
    a("> re-run the script to refresh.\n")
    a("## Provenance\n")
    a("- Source: the portal's own Supabase backend, read with the public anon key the")
    a("  portal JS bundle ships (the exact data the gallery renders). Pages repo and")
    a("  `snorkel-tb-tasks` are private (not readable via the user's GitHub).")
    a(f"- Snapshot date: {today} (auto-refresh).")
    a(f"- Rows read: `v_tasks_with_priorities` = {len(V)} (curated/priority tasks, 3-level")
    a(f"  taxonomy); `task_inspiration_v2` = {len(I)} (inspiration pool; is_milestone")
    a(f"  true={mile.get(True,0)} / false={mile.get(False,0)}).")
    a("- The difficulty column on `v_tasks_with_priorities` may be all-null; if so,")
    a("  difficulty is NOT a usable gallery field — gate hardness by model pass-rate.\n")
    a("## Data model — the gallery MERGES two sources\n")
    a("`/portal/tasks` concatenates:")
    a("1. **`v_tasks_with_priorities`** — `category` → `subcategory` → `subsubcategory`")
    a("   (3-level tree below) + `difficulty` (easy|medium|hard, UI = 1/2/3 dots).")
    a("2. **`task_inspiration_v2`** — `type` (= category) + `subtypes` (the 5 cross-cutting")
    a("   axes) + `languages`, mapped into the card as `category=type`,")
    a("   `subcategory=subtypes.join(', ')`.\n")
    a("Two orthogonal axes therefore exist; record BOTH where they apply: the **3-level")
    a("category taxonomy** AND zero-or-more of the **5 subtypes**.\n")

    a("## Categories (canonical name ⇄ skill kebab alias)\n")
    a("`v_tasks_with_priorities` carries the curated categories; `task_inspiration_v2`")
    a("may add **Large Codebase Tasks** (milestone-heavy large multi-layer repos).\n")
    a("| Canonical gallery category | skill kebab alias | curated rows | inspiration rows |")
    a("|---|---|---:|---:|")
    allcats = sorted(set(list(vcat) + list(itype)), key=lambda c: -(vcat.get(c, 0) + itype.get(c, 0)))
    for c in allcats:
        a(f"| {c} | `{KEBAB.get(c, '?')}` | {vcat.get(c,0)} | {itype.get(c,0)} |")
    a("")

    a("## 5 cross-cutting subtypes (`task_inspiration_v2.subtypes`)\n")
    a("Orthogonal to category; a task has 0+ of these. (Counts across the inspiration pool.)\n")
    for s in FIVE:
        a(f"- **{s}** — {sub5.get(s,0)}")
    extra = [(s, n) for s, n in sub5.most_common() if s not in FIVE]
    if extra:
        a("\nThe **Large Codebase Tasks** type instead uses milestone subtypes:")
        a("  " + ", ".join(f"{s} ({n})" for s, n in extra) + ".\n")

    a("## Language distribution (`task_inspiration_v2.languages`, top 30)\n")
    a("Evidence for the \"mix languages, archetype-first\" rule.\n")
    a("| lang | n | | lang | n | | lang | n |")
    a("|---|---:|---|---|---:|---|---|---:|")
    top = langs.most_common(30)
    for i in range(0, len(top), 3):
        cells = [f"{l} | {n}" for l, n in top[i:i + 3]]
        while len(cells) < 3:
            cells.append(" | ")
        a("| " + " | | ".join(cells) + " |")
    a("")

    a("## Full 3-level taxonomy tree (`v_tasks_with_priorities`)\n")
    a("`### category` → `• subcategory (rows)` → `- subsubcategory [rows]`. Leaves with")
    a("`[1]` are near-empty (high-novelty targets, or label variants of a sibling).\n")
    for c in sorted(tree):
        a(f"### {c}  ({vcat.get(c,0)})")
        for s in sorted(tree[c]):
            sss = tree[c][s]
            a(f"- **{s}**  ({sum(sss.values())})")
            for ss in sorted(sss):
                a(f"    - {ss}  [{sss[ss]}]")
        a("")
    return "\n".join(o) + "\n"


def main():
    today = datetime.date.today().isoformat()
    print(f"[refresh] discovering live Supabase backend from {SITE} ...")
    sb, key = discover()
    print(f"[refresh] backend={sb}  anon-key={key[:18]}…")
    V = fetch_all(sb, key, "v_tasks_with_priorities",
                  "category,subcategory,subsubcategory,difficulty")
    I = fetch_all(sb, key, "task_inspiration_v2", "type,subtypes,languages,is_milestone")
    print(f"[refresh] rows: v_tasks_with_priorities={len(V)}  task_inspiration_v2={len(I)}")
    md = build_markdown(V, I, today)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(md)
    print(f"[refresh] wrote {OUT} ({md.count(chr(10))} lines, {today})")


if __name__ == "__main__":
    main()
