import json
C = []
def c(id, script, inp="", opts=(), files=None, **kw):
    d = {"id": id, "opts": list(opts), "script": script, "input": inp}
    if files is not None: d["files"] = files
    d.update(kw); C.append(d)
A45 = "a" * 45 + "\n"
c("F5", "s/(a|aa)*b/X/", A45, ["-E"])
c("F5b", "s/\\(a*\\)*b/X/", "a"*30+"\n")
c("F5c", "s/(a|b|ab)*c/X/", "ab"*20+"\n", ["-E"])
c("F6", "/A/h; /B/{g;p}", "", ["-s", "-n"], [["f1", "A\n"], ["f2", "B\n"]])
c("F10", "/A/h;/B/g;p", "", ["-s", "-n"], [["f1", "A\n"], ["f2", "B\n"]])
c("F10b", "/A/h;/B/G;p", "", ["-s", "-n"], [["f1", "A\n"], ["f2", "B\n"]])
c("F7", "/A/,/Z/p;n", "", ["-s", "-n"], [["f1", "A\n"], ["f2", "B\nC\n"]])
c("F7b", "/A/,/Z/p;n", "", ["-n"], [["f1", "A\n"], ["f2", "B\nC\n"]])
c("F8", "s/(a|aa)(a?)/<\\1:\\2>/", "aa\n", ["-E"])
c("F13", "s/(a|aa)(a?)/[\\1]/", "aa\n", ["-E"])
c("F27", "s/\\(a\\|aa\\)\\(a\\?\\)/[\\1]/", "aa\n")
c("F9", "1{N;s/a/A/;D};t ok;b;:ok;p", "a\nb\n", ["-n"])
c("F11", "1{N;s/a/A/;D};T bad;p;:bad", "a\nb\n", ["-n"])
c("F12", "y/\\r/X/", "a\rb\n")
c("F14", "s/\\(a\\)\\1/X/I", "aA\n")
c("F14i", "s/\\(a\\)\\1/X/i", "aA\n")
c("F16", "/\\(a\\)\\1/Ip", "aA\n", ["-n"])
c("F24", "s/(a)\\1/X/I", "aA\n", ["-E"])
c("F15", "1,3c X", "a\n")
c("F15b", "2,/zz/c X", "a\nb\nc\n")
c("F15c", "1,3c\\\nX", "a\nb\n")
c("F17", "N;p", "", ["-s", "-n"], [["f1", "a\n"], ["f2", "b\n"]])
c("F17b", "$!N;p", "", ["-s", "-n"], [["f1", "a\n"], ["f2", "b\n"]])
c("F18", "s/a^b/X/p", "a^b\n", ["-E", "-n"])
c("F19", "s/a$b/X/p", "a$b\n", ["-E", "-n"])
c("F18b", "s/a^b/X/", "a^b\n")
c("F19b", "s/a$b/X/", "a$b\n")
c("F20", "/[-a]/p", ".\n", ["-n"])
c("F20b", "s/[-a]/X/g", "-a.b\n")
c("F22", "2a A\n2,4c\\\nX", "1\n2\n3\n4\n5\n")
c("F26", "s/a/a/;T x;T y;:x;s/^/X/;b e;:y;s/^/Y/;:e;p", "a\n", ["-n"])
c("F76", "0p", "x\n")
c("F76b", "0,3p", "x\n")
# verifier coverage probes
c("V1i", "i TEXT", "x\n"); c("V1c", "c TEXT", "x\n")
c("V2", "s/a/X/i", "A\n"); c("V2m", "N;s/^b/X/m", "a\nb\n")
c("V3", "s/[[=a=]]/X/g", "a\n")
c("V4", "s/\\(b\\?\\)-/\\u\\1x/g", "a-b-\n")
c("V44", "s/\\(b\\?\\)-/x\\u\\1/g", "a-b-\n")
c("V29", "$p", "", ["-s", "-n"], [["e", ""], ["f", "a\n"]])
c("V32", "p", "a\n", [], [["-", None]])
c("V33", "l", "a"*80 + "\n", ["-n"])
c("V37", "l", "a"*71 + "\n", ["-n"])
c("V37b", "l", "a"*69 + "\n", ["-n"])
c("V34", "1a hello;2d", "a\nb\n")
c("V35", "  s/o/O/", "one\n")
c("V38", "s/a/A/;t done;:done;t skip;s/$/X/;:skip", "a\n")
c("V39", "s/a/A/;t;s/$/X/", "a\n"); c("V39b", "T;s/$/X/", "a\n")
c("V40", "s/\\(a\\)\\(b\\)\\(c\\)/\\3/", "abc\n")
c("V41", "s/\\(a\\)\\(b\\)\\(c\\)\\(d\\)\\(e\\)\\(f\\)\\(g\\)\\(h\\)\\(i\\)/\\9/", "abcdefghi\n")
c("V42", "s#/#X#", "/\n")
c("V43", "s/a/\\LAb\\UCd/", "a\n")
c("V45", "s/a/x\\\ny/", "a\n")
c("V47", "N;s/./X/Mg", "a\nb\n"); c("V47m", "N;s/./X/mg", "a\nb\n")
c("V49", "a hi;d", "x\n")
c("V50", "a X\nN;d", "a\nb\n")
c("V51", "a\\\nA\\\nB", "x\n")
c("V52a", "a\\\n\\\\", "x\n"); c("V52i", "i\\\n\\\\", "x\n")
c("V53", "2i  NEW", "a\nb\n"); c("V54", "2c  NEW", "a\nb\n")
c("V55", "1c\\", "x\n", extra=[], opts=["-e", "1c\\", "-e", "CHANGED"], script_arg=None)
c("V57", "b target ;s/x/wrong/;:target;s/x/ok/", "x\n")
c("V58", "3~2p", "1\n2\n3\n4\n5\n", ["-n"])
c("V59", "/a|b/p", "b\n", ["-E", "-n"])
c("V60", "/a\\/b/p", "a/b\n", ["-n"]); c("V60b", "\\%a\\%b%p", "a%b\n", ["-n"])
c("V61", "N;/^b/Mp", "a\nb\n", ["-n"])
c("V62", "/b/id", "b\n", ["-n"])
c("V63", "s/a?b/X/", "a?b\n"); c("V63e", "s/a\\+b/X/", "a+b\n", ["-E"])
c("V64", "s/a**/X/", "aa\n")
c("V66", "s/[a-c]/X/", "c\n")
c("V67", "s/a/b/", "a\n", script_arg=True)
c("V69", "h;s/x/y/;g", "x\n")
c("V71", "# ignored ; 2d", "a\nb\n")
c("V72", "a \\\\", "x\n"); c("V74", "i \\\\", "x\n")
c("V73", "1,2i X", "a\nb\n")
c("V75", "s/\\(*\\)/X/", "*\n")
c("V77", "13p", "".join(f"{i}\n" for i in range(1, 30)), ["-n"])
c("V78", "y/a/\\\n/", "a\n")
json.dump(C, open("probe.json", "w"), indent=0)
